### ISSUE TITLE
Reference group "MUT"

### ISSUE THREAD

**Issue by joowkim** [bioinformatics-core-shared-training/Bulk_RNAseq_Course_Base#19]
Hello,

It seems to me that the reference/baseline is "WT" instead of "MUT". 

This is how the meta data is made.
`colData(dds) <- DataFrame(treatment = factor(rep(c("A", "B"), each = 6)),
                          genotype = factor(rep(c("WT", "MUT"), 6), 
                                            levels = c("WT", "MUT")),
                          row.names = paste0("sample", 1:12))`

The code here, `The levels = c("WT, "MUT")`, "WT" comes first, and model.matrix says something similar. 

https://github.com/bioinformatics-core-shared-training/Bulk_RNAseq_Course_Base/blob/181df86fbe88d037ea3bcbf324fb98786f64bb1b/Markdowns/07_Linear_Models.Rmd#L962

**Comment by tavareshugo** [comment]
Many thanks for opening this issue @joowkim 
You were absolutely right, and we have fixed this now.
