### ISSUE TITLE
Improvements to new stats and linear models sessions

### ISSUE THREAD

**Issue by tavareshugo** [bioinformatics-core-shared-training/Bulk_RNAseq_Course_Base#2]
First run of this was on the [June 2021 course](https://github.com/bioinformatics-core-shared-training/Bulk_RNAseq_Course_2021_June). 

- 1st part (stats) took 50 min (13:15 - 14:05)
- 2nd part (linear models) ran over, at total of 2h (14:10 - 16:10)
  - Started exercise 2 at 14:40 
  - Started exercise 4 at 15:30
  - Skipped exercise 5 and DESeq details. 

Some ideas for future improvements: 

- Skip DESeq2 code in linear models session  (since DESeq2 code is then introduced in the next session). We can leave it in the handout, but remove it from the slides. All we need to explain is the results table and how DESeq names the coefficients. 
- In the linear models slides, include the the [models image](https://github.com/bioinformatics-core-shared-training/Bulk_RNAseq_Course_2021_June/blob/master/images/AdditiveAndInteractionModels.svg), which appears throughout the materials at different points (e.g. use in the summary slide).
- In the Stats lecture, make clearer the relationship between test statistics and p-values. Similar to what Dom had in his materials, explaining that statisticians derived that these test statistics follow some asymptotic distribution, which can then be used to calculate the p-value.

**Comment by tavareshugo** [comment]
Student feedback suggests that some of the exercises in the linear models section are too easy. 
Think about having some differentiation with easier and (optional) harder exercises.

**Comment by tavareshugo** [comment]
Can we redesign the materials somehow so that the sessions are a bit more interwoven (and perhaps shorten the total time needed for them)? 
At the moment we have stats slides followed by "linear models" slides. But this ends up being quite intensive. Also, there is some redundancy with the [Introduction slides](https://bioinformatics-core-shared-training.github.io/Bulk_RNASeq_Course_Nov21/Bulk_RNAseq_Course_Base/Markdowns/06_Introduction_to_RNAseq_Analysis_in_R.html#1).

For example, could we somehow integrate the linear models session with practical DESeq? So that we alternate between slides and R more with exercises along the way. 
For example:

- stats slides go through the model considerations (size factors, dispersion, NB GLM, Wald test) 
- go to R and do these steps
- then cover the basic model with one factor two levels
- back to R and show the "results" function
- then additive model with two factors
- back to R for the additive model
- back to slides for interaction model
- back to R for interaction model
  - here there could be a longer exercise to extract different contrasts of interest

**Comment by AshKernow** [comment]
Closing this as  some of these have been implemented and we will be taking a look at so,e other changes for the stats section
