### ISSUE TITLE
Shorten/improve day 3 recap slides (before DESeq2 differential analysis)

### ISSUE THREAD

**Issue by tavareshugo** [bioinformatics-core-shared-training/Bulk_RNAseq_Course_Base#4]
This refers to the [Nov 2021 slides](https://docs.google.com/presentation/d/1XBfQ7ryZlLUuFOBEtwmmuzbB4sp_efaHvSi6Fab7sPs/edit?usp=sharing). 

- Shorten the presentation by removing some of the first few slides, to focus more on the DESeq2-relevant parts
- Keep workflow overview (maybe use the same image as the rest of the slides)
- Keep slide 8 (DESeqDataSet object overview)
- Then from slide 10 onwards 
- Add slide reminding people of the LRT test (maybe make it explicitly about the design of the experiment in the course)

**Need to get this down to 30min**

**Comment by AshKernow** [comment]
Closing this as the slides are now different as we have changed the schedule so DESeq2 is now on day 2.
