### ISSUE TITLE
Clarify role of genome alignments

### ISSUE THREAD

**Issue by TomSmithCGAT** [bioinformatics-core-shared-training/Bulk_RNAseq_Course_Base#9]
I think it's currently a little unclear what the purpose of the genome alignments is in the workflow that's being presented.

The workflow slide itself appears to describe a linear process from raw reads -> aligned reads -> quantification -> etc which I think is part of the issue. I suggest 

- Updating the workflow to indicate the branching nature of the analysis
- Clarifying why we need to align to perform full QC on the reads, e.g what can we get from raw, what can we get from the quantification, what do we need alignment for

**Comment by AshKernow** [comment]
We are no longer doing the genomic alignment in the course
